"""
Secrets Stack — AWS Secrets Manager for all application credentials.

Secrets are created as EMPTY PLACEHOLDERS. Populate them before the first deploy:
  python scripts/setup_secrets.py --stage dev

Empty secrets fail loudly at startup (SecretString is empty JSON "{}"),
which is safer than shipping template values that look real.

Note: DB credentials are created by DatabaseStack (auto-generated by RDS).
"""
import aws_cdk as cdk
from aws_cdk import (
    Stack,
    aws_secretsmanager as secretsmanager,
    CfnOutput,
)
from constructs import Construct


def _empty_secret(
    stack: Stack,
    construct_id: str,
    secret_name: str,
    description: str,
) -> secretsmanager.Secret:
    """Create a Secrets Manager secret with an empty JSON body placeholder."""
    return secretsmanager.Secret(
        stack, construct_id,
        secret_name=secret_name,
        description=description,
        # generate_secret_string generates a random password we don't want.
        # secret_string_value with a minimal placeholder avoids unsafe_plain_text
        # on real credentials while making it obvious the secret needs population.
        secret_string_value=cdk.SecretValue.unsafe_plain_text("{}"),
    )


class SecretsStack(Stack):
    def __init__(self, scope: Construct, id: str, stage: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        self.stage = stage

        # ── JWT Keys ──────────────────────────────────────────────────────────
        # Expected structure after setup_secrets.py:
        # { "private_key": "-----BEGIN RSA PRIVATE KEY-----...",
        #   "public_key":  "-----BEGIN PUBLIC KEY-----...",
        #   "algorithm": "RS256",
        #   "access_token_expire_minutes": "15",
        #   "refresh_token_expire_days": "30",
        #   "google_client_ids": ["<ios-client-id>", "<android-client-id>"] }
        self.jwt_secret = _empty_secret(
            self, "JwtSecret",
            secret_name=f"acollya/{stage}/jwt",
            description="Acollya JWT RS256 keys + Google client IDs — run setup_secrets.py",
        )

        # ── OpenAI ────────────────────────────────────────────────────────────
        # Expected: { "api_key": "sk-...", "chat_model": "gpt-4o-mini",
        #             "embedding_model": "text-embedding-3-small", "max_tokens": "1024" }
        self.openai_secret = _empty_secret(
            self, "OpenAiSecret",
            secret_name=f"acollya/{stage}/openai",
            description="OpenAI API credentials — run setup_secrets.py",
        )

        # ── Anthropic ─────────────────────────────────────────────────────────
        # Expected: { "api_key": "sk-ant-...", "chat_model": "claude-haiku-4-5-20251001" }
        self.anthropic_secret = _empty_secret(
            self, "AnthropicSecret",
            secret_name=f"acollya/{stage}/anthropic",
            description="Anthropic API credentials — run setup_secrets.py",
        )

        # ── App Config ────────────────────────────────────────────────────────
        # Expected: { "trial_days": "14", "free_chat_messages_per_day": "20",
        #             "premium_chat_messages_per_day": "9999",
        #             "revenue_cat_api_key": "..." }
        self.app_config_secret = _empty_secret(
            self, "AppConfigSecret",
            secret_name=f"acollya/{stage}/app-config",
            description="Acollya application configuration — run setup_secrets.py",
        )

        # ── Expose ARNs ───────────────────────────────────────────────────────
        CfnOutput(self, "JwtSecretArn", value=self.jwt_secret.secret_arn, export_name=f"AcollyaJwtSecretArn-{stage}")
        CfnOutput(self, "OpenAiSecretArn", value=self.openai_secret.secret_arn, export_name=f"AcollyaOpenAiSecretArn-{stage}")
        CfnOutput(self, "AnthropicSecretArn", value=self.anthropic_secret.secret_arn, export_name=f"AcollyaAnthropicSecretArn-{stage}")
