"""
Secrets Stack — AWS Secrets Manager for all application credentials.

Secrets created here are PLACEHOLDERS. After deploying, populate them via:
  python scripts/setup_secrets.py --stage dev

Secrets:
  - acollya/{stage}/jwt            → JWT signing keys (RS256)
  - acollya/{stage}/openai         → OpenAI API key
  - acollya/{stage}/stripe         → Stripe secret + webhook signing keys
  - acollya/{stage}/google-oauth   → Google OAuth client credentials
  - acollya/{stage}/app-config     → App-level config (trial days, limits)

Note: DB credentials are created by DatabaseStack (auto-generated by RDS).
"""
import json
import aws_cdk as cdk
from aws_cdk import (
    Stack,
    aws_secretsmanager as secretsmanager,
    CfnOutput,
)
from constructs import Construct


class SecretsStack(Stack):
    def __init__(self, scope: Construct, id: str, stage: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        self.stage = stage

        # ── JWT Keys ──────────────────────────────────────────────────────────
        # Store RS256 private + public key (PEM format)
        # Generate with: openssl genrsa -out jwt_private.pem 2048
        self.jwt_secret = secretsmanager.Secret(
            self, "JwtSecret",
            secret_name=f"acollya/{stage}/jwt",
            description="Acollya JWT RS256 signing keys",
            secret_object_value={
                "private_key": cdk.SecretValue.unsafe_plain_text("REPLACE_WITH_RS256_PRIVATE_KEY"),
                "public_key": cdk.SecretValue.unsafe_plain_text("REPLACE_WITH_RS256_PUBLIC_KEY"),
                "algorithm": cdk.SecretValue.unsafe_plain_text("RS256"),
                "access_token_expire_minutes": cdk.SecretValue.unsafe_plain_text("15"),
                "refresh_token_expire_days": cdk.SecretValue.unsafe_plain_text("30"),
            },
        )

        # ── OpenAI ────────────────────────────────────────────────────────────
        self.openai_secret = secretsmanager.Secret(
            self, "OpenAiSecret",
            secret_name=f"acollya/{stage}/openai",
            description="OpenAI API credentials",
            secret_object_value={
                "api_key": cdk.SecretValue.unsafe_plain_text("REPLACE_WITH_OPENAI_KEY"),
                "chat_model": cdk.SecretValue.unsafe_plain_text("gpt-4o-mini"),
                "embedding_model": cdk.SecretValue.unsafe_plain_text("text-embedding-3-small"),
                "max_tokens": cdk.SecretValue.unsafe_plain_text("1024"),
            },
        )

        # ── Stripe ────────────────────────────────────────────────────────────
        self.stripe_secret = secretsmanager.Secret(
            self, "StripeSecret",
            secret_name=f"acollya/{stage}/stripe",
            description="Stripe payment credentials",
            secret_object_value={
                "secret_key": cdk.SecretValue.unsafe_plain_text("REPLACE_WITH_STRIPE_SECRET_KEY"),
                "webhook_secret": cdk.SecretValue.unsafe_plain_text("REPLACE_WITH_STRIPE_WEBHOOK_SECRET"),
                "price_id_monthly": cdk.SecretValue.unsafe_plain_text("REPLACE_WITH_STRIPE_PRICE_ID"),
                "price_id_yearly": cdk.SecretValue.unsafe_plain_text("REPLACE_WITH_STRIPE_YEARLY_PRICE_ID"),
            },
        )

        # ── Google OAuth ──────────────────────────────────────────────────────
        self.google_secret = secretsmanager.Secret(
            self, "GoogleOAuthSecret",
            secret_name=f"acollya/{stage}/google-oauth",
            description="Google OAuth 2.0 credentials",
            secret_object_value={
                "client_id": cdk.SecretValue.unsafe_plain_text("REPLACE_WITH_GOOGLE_CLIENT_ID"),
                "client_secret": cdk.SecretValue.unsafe_plain_text("REPLACE_WITH_GOOGLE_CLIENT_SECRET"),
            },
        )

        # ── App Config ────────────────────────────────────────────────────────
        self.app_config_secret = secretsmanager.Secret(
            self, "AppConfigSecret",
            secret_name=f"acollya/{stage}/app-config",
            description="Acollya application configuration",
            secret_object_value={
                "trial_days": cdk.SecretValue.unsafe_plain_text("14"),
                "free_chat_messages_per_day": cdk.SecretValue.unsafe_plain_text("20"),
                "premium_chat_messages_per_day": cdk.SecretValue.unsafe_plain_text("9999"),
                "revenue_cat_api_key": cdk.SecretValue.unsafe_plain_text("REPLACE_WITH_REVENUECAT_KEY"),
            },
        )

        # ── Expose ARNs ───────────────────────────────────────────────────────
        CfnOutput(self, "JwtSecretArn", value=self.jwt_secret.secret_arn, export_name=f"AcollyaJwtSecretArn-{stage}")
        CfnOutput(self, "OpenAiSecretArn", value=self.openai_secret.secret_arn, export_name=f"AcollyaOpenAiSecretArn-{stage}")
        CfnOutput(self, "StripeSecretArn", value=self.stripe_secret.secret_arn, export_name=f"AcollyaStripeSecretArn-{stage}")
